bump_version: null
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-customnofastqc_logo_light.png
  - docs/images/nf-core-customnofastqc_logo_light.png
  - docs/images/nf-core-customnofastqc_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-customnofastqc_logo_light.png
  - docs/images/nf-core-customnofastqc_logo_light.png
  - docs/images/nf-core-customnofastqc_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
nf_core_version: 2.14.2.dev0
org_path: null
repository_type: pipeline
template:
  author: mirpedrol
  description: this is a custom pipeline where fastqc has been removed and should
    not be added by the new template update
  force: false
  is_nfcore: false
  name: customnofastqc
  org: mirpedrol
  outdir: .
  skip_features:
  - fastqc
  version: 1.0dev
update: null
